# Generated by Django 3.2 on 2021-04-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20210421_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.JSONField(max_length=10),
        ),
    ]
